### ISSUE TITLE
its not an issue help required 

### ISSUE THREAD

**Issue by prashantnirgun** [ky-is/vitepress-starter-tailwind#1] opened 2022-02-19 17:30 UTC
Hi

Thanks for the repo I am going to use tailwind first time so its found to be a great repo for me. Good work keep it up. I just need help when I build the project it was showing me the warning can you help me to fix the issue

warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css

is it because of tailwind.config.js https://codybontecou.com/tailwindcss-with-vitepress.html

**Comment by ky-is** [comment] 2022-02-19 19:58
I updated the dependencies and added support for Tailwind v3's `content`-based purge approach. If you're still having any issues let me know!

**Comment by prashantnirgun** [comment] 2022-02-20 07:25
I updated tailwind 3 and it broke 
12:52:10 pm [vite] Internal server error: Cannot read property 'config' of undefined
  Plugin: vite:css
  File: /vitepress/docs/.vitepress/theme/tailwind.postcss
      at getTailwindConfig (/vitepress/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:81:62)
      at /vitepress/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:124:92
      at /vitepress/node_modules/tailwindcss/lib/processTailwindFeatures.js:43:11
      at plugins (/vitepress/node_modules/tailwindcss/lib/index.js:20:104)
      at LazyResult.runOnRoot (/vitepress/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/vitepress/node_modules/postcss/lib/lazy-result.js:393:26)
      at LazyResult.async (/vitepress/node_modules/postcss/lib/lazy-result.js:221:30)
      at LazyResult.then (/vitepress/node_modules/postcss/lib/lazy-result.js:206:17)
12:52:10 pm [vite] Internal server error: Cannot read property 'config' of undefined

however my config.js
```module.exports = {
  title: "TSS",
  description: "software",
  themeConfig: {
    repo: "",
    editLinks: false,
    docsDir: "",
    editLinkText: "",
    lastUpdated: false,
    nav: [
      {
        text: "Training",
        items: [{ text: "BPP Desktop", link: "/training/bpp-desktop" }],
      },
    ],
  },
};
```

**Comment by prashantnirgun** [comment] 2022-02-20 08:08
wait something broken with yarn I raised a ticket https://github.com/vuejs/vitepress/issues/544

**Comment by prashantnirgun** [comment] 2022-02-20 11:46
yarn run v1.22.17
$ vitepress build docs
vitepress v0.22.2
⠴ building client + server bundles...
warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
✓ building client + server bundles...
✓ rendering pages...
build complete in 27.72s.
Done in 28.26s.

Thanks this get build with some warning

**Comment by ky-is** [comment] 2022-02-20 14:57
You'll need to use Tailwindcss v3 now for this to work out of the box. Otherwise follow the docs for v2 here: https://v2.tailwindcss.com/docs/optimizing-for-production#purge-css-options

**Comment by prashantnirgun** [comment] 2022-02-21 05:13
No I updated Tailwing 3 and warning still there on build. 
Beside I see <a herf="/" class="no-underline">Root</a>  still it shows underline

**Comment by ky-is** [comment] 2022-03-02 16:39
A clean clone and build works as intended for me, so going to close this for now. If you're still encountering bugs do share the logs, thanks!

**Closed as completed by ky-is** 2022-03-02 16:39 UTC
